### ISSUE TITLE
Consider Boost License

### ISSUE THREAD

**Issue by Downchuck** [mleise/fast#2]
Many D-language projects are licensed with the Boost license. fast is currently under a GPL3.0 license which would require any user of the project also license their project under GPL3.0.

This consideration came up via the announcement thread on the dlang forums: 
http://forum.dlang.org/thread/20151014090114.60780ad6@marco-toshiba?page=2

**Comment by cheese-stands-alone** [comment]
+1

**Comment by mleise** [comment]
Truth be told, I would consider any license that allows improvement on the program code by fellow programmers and puts restrictions on how free labor can be used in commercial projects without compensation. Yet I settled for GPL3.0, which is mostly about making sure that when you distribute software, the open source portions can be modified, fixed and recompiled. As such it can not be used in projects imposing limits on this, but is compatible with using additional Boost licensed code. You have the choice.

**Comment by Downchuck** [comment]
@mleise I think that last part "commercial projects" is the catch - it sounds like you are firm on the GPL3 license.  D and its standard libraries are available under Boost license, which allows for commercial entities to compile the code without carrying license restrictions.

I'll go ahead and close out this issue.
