### ISSUE TITLE
json: C strings concept is not valid

### ISSUE THREAD

**Issue by 9il** [mleise/fast#4]
The validation is wrong fot D strings.

``` D
            static if (isValidating)
                if (*m_text != '\0')
```

**Comment by mleise** [comment]
Thank you for the quick review.

``` D
static if (isValidating)
    if (*m_text != '\0')
        handleError("Expected end of JSON.");
```

That's not a C-string terminating `\0` check. `Json` structs must be created with a string ending in `\0` plus 15 more bytes, for this check and in particular all SSE optimizations to work. This preparation is handled in the `parse[Trusted]JSON[File]()` functors. There are three approaches to preparing the string:
- Someone already has the string prepared and passes it to the `Json` ctor.
- A string is parsed: 16 `\0` are appended by fast.json.
- A file is parsed: Memory mapping tricks add `\0` bytes.

For that reason, I have not moved the work into the `Json` ctor. It is mostly a matter of missing documentation and questionable API design on my end. I could provide an additional ctor argument that defaults to appending zeroes to the string, making them save to call in the general case. It really doesn't buy you anything over using the functors, which are meant to be focused on use cases.

**Comment by 9il** [comment]
BTW, how this error can happen ? 

```
core.exception.SwitchError@fast.json(1089): No appropriate switch clause found
```

It happens only with `trustedSource`.

**Comment by mleise** [comment]
Since it doesn't happen with validation, the quick&dirty parsing for trusted sources must have overlooked something important in the JSON file and ended up at at the wrong spot, expecting a value where EOF or a delimiting character is. Do you have a test case for me that I could add to the unittests?

**Comment by 9il** [comment]
``` D
import fast.json;
auto str = `{"initiator_carrier_code":null,"a":"b"}`;
auto js = Json!trustedSource(str);
foreach(key; js.byKey)
{
    if(key == "initiator_carrier_code")
    {
        auto t = js.read!string;
        writeln(t);
    }
    else
    {
        writeln(key);
        js.skipValue();
    }
}
```

**Comment by mleise** [comment]
The wrong flag in the `null`-reading function caused it to work in validating mode, resulting in the following ',' not being skipped as expected. The comma in turn did not match any pattern for JSON values in the switch-case. Fixed now in master.
